Ludlow/test branch
slashrelativepath/relativepath-cycle-5 pull request #15
Opened 2023-09-20 00:10 UTC by Topher2014

Added Arch script. 
Added Arch to readme instructions

2023-09-20 16:37 UTC, ChrisForti commented on README.md
> +On Arch linux, the best linux, run this:
😂

2023-09-20 16:37 UTC, ChrisForti commented on webserver-archlinux.sh
> +    sudo snap install multipass
Why the same command twice?

2023-09-20 21:43 UTC, stephenlauck requested changes
We should make sure we're not deleting the work we have done in the darwin script. Otherwise, this is interesting and ok to merge.

2023-09-20 21:43 UTC, stephenlauck commented on README.md
> +On Arch linux, the best linux, run this:
haha :+1:

2023-09-20 21:43 UTC, stephenlauck commented on webserver-archlinux.sh
> +    case $yn in
Weeeeeee! Ok, going with some nested complexity!

2023-09-20 21:43 UTC, stephenlauck commented on webserver-darwin.sh
um, why deleted?

2023-09-25 22:52 UTC, ChrisForti approved these changes
👍🏼

2023-09-25 22:53 UTC, stephenlauck approved these changes

2023-09-25 22:54 UTC, merged